---
title: "Address Form Validator"
type: "challenge"  # challenge, exercise, article, video
description: "Validate form fields using JavaScript."
tags: "javascript"
ignore:
- "address-form-validator.md"
